package broker

// Log event names. One declaration; call sites use these names.

LOG_EVENT_ACCEPT_FAILED :: "accept_failed"
LOG_EVENT_AUTH_FAILED :: "auth_failed"
LOG_EVENT_CONNECT_FAILED :: "connect_failed"
LOG_EVENT_CONNECT_OK :: "connect_ok"
LOG_EVENT_DRAIN_COMPLETE :: "drain_complete"
LOG_EVENT_DRAIN_STARTED :: "drain_started"
LOG_EVENT_LIMIT_EXCEEDED :: "limit_exceeded"
LOG_EVENT_PROTOCOL_ERROR :: "protocol_error"
LOG_EVENT_REGISTER_FAILED :: "register_failed"
LOG_EVENT_ROLE_VIOLATION :: "role_violation"
LOG_EVENT_SERVICE_REGISTERED :: "service_registered"
LOG_EVENT_SERVICE_UNREGISTERED :: "service_unregistered"
LOG_EVENT_SESSION_AUTHENTICATED :: "session_authenticated"
LOG_EVENT_SESSION_CLOSED :: "session_closed"
LOG_EVENT_STREAM_RESET :: "stream_reset"
LOG_EVENT_UNREGISTER_FAILED :: "unregister_failed"

// Shared log/metric reason and limit labels.

LABEL_UNKNOWN :: "unknown"

LABEL_AGENT :: "agent"
LABEL_CALLER :: "caller"

LABEL_PEER :: "peer"
LABEL_IDLE_TIMEOUT :: "idle_timeout"
LABEL_PROTOCOL_ERROR :: "protocol_error"
LABEL_STREAM_NOT_FOUND :: "stream_not_found"
LABEL_STREAM_BUFFER :: "stream_buffer"
LABEL_CONNECTION_BUFFER :: "connection_buffer"
LABEL_CALLER_GONE :: "caller_gone"
LABEL_AGENT_GONE :: "agent_gone"
LABEL_BROKER_DRAINING :: "broker_draining"
LABEL_STREAM_IDLE :: "stream_idle"
LABEL_GRANT_EXPIRED :: "grant_expired"
LABEL_GRANT_REVOKED :: "grant_revoked"
LABEL_LEASE_EXPIRED :: "authorization_lease_expired"

LABEL_STREAMS_PER_SESSION :: "streams_per_session"
LABEL_REGISTRATIONS_PER_SESSION :: "registrations_per_session"
LABEL_PHYSICAL_CONNECTIONS :: "physical_connections"
LABEL_CONNECTIONS_PER_IP :: "connections_per_ip"
LABEL_FRAME_PAYLOAD :: "frame_payload"
LABEL_GLOBAL_BUFFER :: "global_buffer"
LABEL_FILE_DESCRIPTORS :: "file_descriptors"

LABEL_INVALID_SERVICE_ID :: "invalid_service_id"
LABEL_SERVICE_NOT_FOUND :: "service_not_found"
LABEL_UNAUTHORIZED :: "unauthorized"
LABEL_QUOTA :: "quota"
LABEL_AGENT_UNAVAILABLE :: "agent_unavailable"
LABEL_LOCAL_SERVICE_UNAVAILABLE :: "local_service_unavailable"
LABEL_QUOTA_EXCEEDED :: "quota_exceeded"
LABEL_INTERNAL_ERROR :: "internal_error"
LABEL_RATE_LIMITED :: "rate_limited"

LABEL_CAPABILITY :: "capability"
LABEL_NAMESPACE :: "namespace"
LABEL_NOT_OWNED :: "not_owned"
LABEL_ALREADY_REGISTERED :: "already_registered"

LABEL_AUTHENTICATION :: "authentication"
LABEL_REGISTRATION :: "registration"
LABEL_CONNECT :: "connect"
LABEL_SERVICE_LOOKUP :: "service_lookup"
LABEL_OPEN_OK :: "open_ok"
LABEL_CONNECT_OK :: "connect_ok"

REASON_AGENT_CONNECT :: "agent_connect"
REASON_AGENT_OPEN :: "agent_open"
REASON_AGENT_REGISTER :: "agent_register"
REASON_AGENT_UNREGISTER :: "agent_unregister"
REASON_AGENT_OPEN_OK :: "agent_open_ok"
REASON_AGENT_OPEN_FAILED :: "agent_open_failed"
REASON_AGENT_OPCODE :: "agent_opcode"
REASON_CALLER_REGISTER :: "caller_register"
REASON_CALLER_UNREGISTER :: "caller_unregister"
REASON_CALLER_OPEN :: "caller_open"
REASON_CALLER_OPEN_OK :: "caller_open_ok"
REASON_CALLER_OPEN_FAILED :: "caller_open_failed"
REASON_CALLER_CONNECT :: "caller_connect"
REASON_CALLER_OPCODE :: "caller_opcode"

DIAGNOSTIC_STREAM_BUFFER_EXCEEDED :: "stream buffer exceeded"
DIAGNOSTIC_CONNECTION_BUFFER_EXCEEDED :: "connection buffer exceeded"
DIAGNOSTIC_GLOBAL_BUFFER_EXCEEDED :: "global buffer exceeded"
